template_path: bridgeserver2.yaml
stack_name: bridgeserver2-prod
parameters:
  AppDeployBucket: org-sagebridge-bridgeserver2-deployment-prod
  AppHealthcheckUrl: '/'
  AttachmentBucket: org-sagebridge-attachment-prod
  AwsAutoScalingMaxSize: "2"
  AwsAutoScalingMinSize: "2"
  AwsEbHealthReportingSystem: enhanced
  AwsKey: !ssm /bridgeserver2-prod/AwsKey
  AwsKeyConsents: !ssm /bridgeserver2-prod/AwsKeyConsents
  AwsKeyUpload: !ssm /bridgeserver2-prod/AwsKeyUpload
  AwsKeyUploadCms: !ssm /bridgeserver2-prod/AwsKeyUploadCms
  AwsSecretKey: !ssm /bridgeserver2-prod/AwsSecretKey
  AwsSecretKeyConsents: !ssm /bridgeserver2-prod/AwsSecretKeyConsents
  AwsSecretKeyUpload: !ssm /bridgeserver2-prod/AwsSecretKeyUpload
  AwsSecretKeyUploadCms: !ssm /bridgeserver2-prod/AwsSecretKeyUploadCms
  AwsSnsBounceNotificationEndpoint: bridge-bounce-notifications@sagebase.org
  AwsSnsNotificationEndpoint: bridgeops@sagebase.org
  BridgeEnv: prod
  BridgeHealthcodeRedisKey: !ssm /bridgeserver2-prod/BridgeHealthcodeRedisKey
  BridgeUser: heroku
  DNSHostname: bridgeserver2-prod
  DNSDomain: sagebridge.org
  EC2InstanceType: t2.medium
  EmailUnsubscribeToken: !ssm /bridgeserver2-common/EmailUnsubscribeToken
  Env: production
  HibernateConnectionPassword: !ssm /bridgeserver2-prod/HibernateConnectionPassword
  HibernateConnectionUrl: !ssm /bridgeserver2-prod/HibernateConnectionUrl
  HibernateConnectionUsername: !ssm /bridgeserver2-prod/HibernateConnectionUsername
  HibernateConnectionUsessl: 'true'
  NewRelicAppName: bridgeserver2-prod
  NewRelicLicenseKey: !ssm /infra/NewRelicLicenseKey
  SnsKey: !ssm /bridgeserver2-prod/SnsKey
  SnsSecretKey: !ssm /bridgeserver2-prod/SnsSecretKey
  SynapseApiKey: !ssm /bridgeserver2-prod/SynapseApiKey
  SynapseUser: !ssm /bridgeserver2-prod/SynapseUser
