template_path: bridgeserver2-antivirus.yaml
stack_name: bridgeserver2-antivirus-prod
parameters:
  CodeZipS3BucketParameter: org-sagebridge-deployments-prod
  CodeZipS3KeyParameter: virus-scanner-lambda-20230206-af70cfc.zip
  ScanTriggerSNSTopicArn: arn:aws:sns:us-east-1:649232250620:virus-scan-trigger-prod
  ScanResultSNSTopicArn: arn:aws:sns:us-east-1:649232250620:virus-scan-result-prod
