template_path: templates/bridgeserver2.yaml
stack_name: bridgeserver2-prod
parameters:
  AppDeployBucket: org-sagebridge-bridgeserver2-deployment-prod
  AppHealthcheckUrl: '/'
  AwsAutoScalingMaxSize: "3"
  AwsAutoScalingMinSize: "3"
  AwsEbHealthReportingSystem: enhanced
  AwsSnsBounceNotificationEndpoint: bridge-bounce-notifications@sagebase.org
  AwsSnsNotificationEndpoint: bridgeops@sagebase.org
  AwsSolutionStackName: '64bit Amazon Linux 2018.03 v3.0.1 running Tomcat 8 Java 8'
  BridgeEnv: prod
  BridgePFStackName: bridgepf-prod
  BridgeUser: heroku
  DNSHostname: bridgeserver2-prod
  DNSDomain: sagebridge.org
  EC2InstanceType: t2.medium
  Env: production
  NewRelicAppName: bridgeserver2-prod
  NewRelicLicenseKey: !ssm /infra/NewRelicLicenseKey
  SSLCertArn: !ssm /bridgeserver2-common/SSLCertArn
