template_path: bridgeserver2.yaml
stack_name: bridgeserver2-prod
depedencies:
  - common/bridgeserver2-common.yaml
  - prod/bridgeserver2-db.yaml
parameters:
  AppDeployBucket: org-biaffectbridge-bridgeserver2-deployment-prod
  AppHealthcheckUrl: '/'
  AttachmentBucket: org-biaffectbridge-attachment-prod
  AwsAutoScalingMaxSize: "2"
  AwsAutoScalingMinSize: "2"
  AwsEbHealthReportingSystem: enhanced
  AwsSnsBounceNotificationEndpoint: biaffect-bridge-bounce-notifications@googlegroups.com
  AwsSnsNotificationEndpoint: biaffect-bridge-ops@googlegroups.com
  BootstrapAdminEmail: !ssm /bridgeserver2-prod/BootstrapAdminEmail
  BootstrapAdminPassword: !ssm /bridgeserver2-prod/BootstrapAdminPassword
  BridgeEnv: prod
  BridgeDBStackName: bridgeserver2-db-prod
  BridgeHealthcodeRedisKey: !ssm /bridgeserver2-prod/BridgeHealthcodeRedisKey
  BridgeUser: biaffect
  BucketSuffix: prod
  DNSHostname: bridgeserver2-prod
  DNSDomain: biaffectbridge.com
  EC2InstanceType: t3a.medium
  Env: production
  ExporterRequestSqsQueueUrl: https://sqs.us-east-1.amazonaws.com/381492192635/Bridge-EX-Request-prod
  ExporterSynapseAccessToken: !ssm /bridgeserver2-prod/ExporterSynapseAccessToken
  ExporterSynapseUser: !ssm /bridgeserver2-prod/ExporterSynapseUser
  HibernateConnectionPassword: !ssm /bridgeserver2-prod/HibernateConnectionPassword
  HibernateConnectionUsername: !ssm /bridgeserver2-prod/HibernateConnectionUsername
  HibernateConnectionUsessl: 'false'
  HostPostfix: .biaffectbridge.com
  SesNotificationTopicArn: arn:aws:sns:us-east-1:381492192635:SNSBounces
  SynapseAccessToken: !ssm /bridgeserver2-prod/SynapseAccessToken
  SynapseUser: !ssm /bridgeserver2-prod/SynapseUser
  SynapseOAuthClientId: !ssm /bridgeserver2-prod/SynapseOAuthClientId
  SynapseOAuthClientSecret: !ssm /bridgeserver2-prod/SynapseOAuthClientSecret
  UddSqsQueueUrl: https://sqs.us-east-1.amazonaws.com/381492192635/Bridge-WorkerPlatform-Request-prod
