template_path: bridgeserver2.yaml
stack_name: bridgeserver2-prod
depedencies:
  - common/bridgeserver2-common.yaml
  - prod/bridgeserver2-db.yaml
parameters:
  AppDeployBucket: org-sagebridge-bridgeserver2-deployment-prod
  AppHealthcheckUrl: '/'
  AttachmentBucket: org-sagebridge-attachment-prod
  AwsAutoScalingMaxSize: "2"
  AwsAutoScalingMinSize: "2"
  AwsEbHealthReportingSystem: enhanced
  AwsSnsBounceNotificationEndpoint: bridge-bounce-notifications@sagebase.org
  AwsSnsNotificationEndpoint: bridgeops@sagebase.org
  BootstrapAdminEmail: !ssm /bridgeserver2-prod/BootstrapAdminEmail
  BootstrapAdminPassword: !ssm /bridgeserver2-prod/BootstrapAdminPassword
  BootstrapApiEmail: !ssm /bridgeserver2-prod/BootstrapApiEmail
  BootstrapApiPassword: !ssm /bridgeserver2-prod/BootstrapApiPassword
  BootstrapSharedEmail: !ssm /bridgeserver2-prod/BootstrapSharedEmail
  BootstrapSharedPassword: !ssm /bridgeserver2-prod/BootstrapSharedPassword
  BridgeEnv: prod
  BridgeDBStackName: bridgeserver2-db-prod
  BridgeHealthcodeRedisKey: !ssm /bridgeserver2-prod/BridgeHealthcodeRedisKey
  BridgeUser: heroku
  ConsentsBucket: org-sagebridge-consents-prod
  DNSHostname: bridgeserver2-prod
  DNSDomain: sagebridge.org
  EC2InstanceType: t2.medium
  EmailUnsubscribeToken: !ssm /bridgeserver2-common/EmailUnsubscribeToken
  Env: production
  ExporterRequestSqsQueueUrl: https://sqs.us-east-1.amazonaws.com/649232250620/Bridge-EX-Request-prod
  HibernateConnectionPassword: !ssm /bridgeserver2-prod/HibernateConnectionPassword
  HibernateConnectionUsername: !ssm /bridgeserver2-prod/HibernateConnectionUsername
  HibernateConnectionUsessl: 'true'
  HostPostfix: .sagebridge.org
  NewRelicAppName: bridgeserver2-prod
  NewRelicLicenseKey: !ssm /infra/NewRelicLicenseKey
  ParticipantFileBucket: org-sagebridge-participantfile-prod
  SesNotificationTopicArn: arn:aws:sns:us-east-1:649232250620:SNSBounces
  SynapseApiKey: !ssm /bridgeserver2-prod/SynapseApiKey
  SynapseUser: !ssm /bridgeserver2-prod/SynapseUser
  SynapseOAuthClientId: !ssm /bridgeserver2-prod/SynapseOAuthClientId
  SynapseOAuthClientSecret: !ssm /bridgeserver2-prod/SynapseOAuthClientSecret
  UddSqsQueueUrl: https://sqs.us-east-1.amazonaws.com/649232250620/Bridge-WorkerPlatform-Request-prod
  UploadBucket: org-sagebridge-upload-prod
  UploadCmsCertBucket: org-sagebridge-upload-cms-cert-prod
  UploadCmsPrivBucket: org-sagebridge-upload-cms-priv-prod
  UsersignedConsentsBucket: bridgepf-prod-awss3usersignedconsentsdownloadbuck-1slz1bcz0mls7
  CrcGeoCodeApiKey: !ssm /bridgeserver2-prod/CrcGeoCodeApiKey
  CuimcTestUsername: !ssm /bridgeserver2-common/CuimcTestUsername
  CuimcTestPassword: !ssm /bridgeserver2-common/CuimcTestPassword
  CuimcProdUsername: !ssm /bridgeserver2-common/CuimcProdUsername
  CuimcProdPassword: !ssm /bridgeserver2-common/CuimcProdPassword
  GbfApiKey: !ssm /bridgeserver2-common/GbfApiKey
