template_path: bridgeserver2-common.yaml
stack_name: bridgeserver2-common
parameters:
  CuimcTestUsername: !ssm /bridgeserver2-common/CuimcTestUsername
  CuimcTestPassword: !ssm /bridgeserver2-common/CuimcTestPassword
  CuimcProdUsername: !ssm /bridgeserver2-common/CuimcProdUsername
  CuimcProdPassword: !ssm /bridgeserver2-common/CuimcProdPassword
