template_path: bridgeserver2.yaml
stack_name: bridgeserver2-develop
depedencies:
  - common/bridgeserver2-common.yaml
  - develop/bridgeserver2-db.yaml
parameters:
  AppDeployBucket: org-sagebridge-bridgeserver2-deployment-develop
  AppHealthcheckUrl: '/'
  AttachmentBucket: org-sagebridge-attachment-develop
  AwsAutoScalingMaxSize: '1'
  AwsAutoScalingMinSize: '1'
  AwsEbHealthReportingSystem: enhanced
  AwsKey: !ssm /bridgeserver2-develop/AwsKey
  AwsKeyConsents: !ssm /bridgeserver2-develop/AwsKeyConsents
  AwsKeyUpload: !ssm /bridgeserver2-develop/AwsKeyUpload
  AwsKeyUploadCms: !ssm /bridgeserver2-develop/AwsKeyUploadCms
  AwsSecretKey: !ssm /bridgeserver2-develop/AwsSecretKey
  AwsSecretKeyConsents: !ssm /bridgeserver2-develop/AwsSecretKeyConsents
  AwsSecretKeyUpload: !ssm /bridgeserver2-develop/AwsSecretKeyUpload
  AwsSecretKeyUploadCms: !ssm /bridgeserver2-develop/AwsSecretKeyUploadCms
  AwsSnsBounceNotificationEndpoint: bridgepf-develop-bounce-notifications@sagebase.org
  AwsSnsNotificationEndpoint: bridgepf-develop@sagebase.org
  BridgeEnv: dev
  BridgeDBStackName: bridgeserver2-db-develop
  BridgeHealthcodeRedisKey: !ssm /bridgeserver2-develop/BridgeHealthcodeRedisKey
  BridgeUser: heroku
  DNSHostname: bridgeserver2-develop
  DNSDomain: sagebridge.org
  EC2InstanceType: t2.small
  EmailUnsubscribeToken: !ssm /bridgeserver2-common/EmailUnsubscribeToken
  Env: develop
  HibernateConnectionPassword: !ssm /bridgeserver2-develop/HibernateConnectionPassword
  HibernateConnectionUrl: !ssm /bridgeserver2-develop/HibernateConnectionUrl
  HibernateConnectionUsername: !ssm /bridgeserver2-develop/HibernateConnectionUsername
  HibernateConnectionUsessl: 'true'
  NewRelicAppName: bridgeserver2-develop
  NewRelicLicenseKey: !ssm /infra/NewRelicLicenseKey
  SnsKey: !ssm /bridgeserver2-develop/SnsKey
  SnsSecretKey: !ssm /bridgeserver2-develop/SnsSecretKey
  SynapseApiKey: !ssm /bridgeserver2-develop/SynapseApiKey
  SynapseUser: !ssm /bridgeserver2-develop/SynapseUser
