template_path: bridgeserver2.yaml
stack_name: bridgeserver2-develop
depedencies:
  - common/bridgeserver2-common.yaml
  - develop/bridgeserver2-db.yaml
parameters:
  AppDeployBucket: org-sagebridge-bridgeserver2-deployment-devdevelop
  AppHealthcheckUrl: '/'
  AttachmentBucket: org-sagebridge-attachment-devdevelop
  AwsAutoScalingMaxSize: '1'
  AwsAutoScalingMinSize: '1'
  AwsEbHealthReportingSystem: enhanced
  AwsSnsBounceNotificationEndpoint: bridgepf-develop-bounce-notifications@sagebase.org
  AwsSnsNotificationEndpoint: bridgepf-develop@sagebase.org
  BootstrapAdminEmail: !ssm /bridgeserver2-develop/BootstrapAdminEmail
  BootstrapAdminPassword: !ssm /bridgeserver2-develop/BootstrapAdminPassword
  BootstrapApiEmail: !ssm /bridgeserver2-develop/BootstrapApiEmail
  BootstrapApiPassword: !ssm /bridgeserver2-develop/BootstrapApiPassword
  BootstrapSharedEmail: !ssm /bridgeserver2-develop/BootstrapSharedEmail
  BootstrapSharedPassword: !ssm /bridgeserver2-develop/BootstrapSharedPassword
  BridgeEnv: dev
  BridgeDBStackName: bridgeserver2-db-develop
  BridgeHealthcodeRedisKey: !ssm /bridgeserver2-develop/BridgeHealthcodeRedisKey
  BridgeUser: heroku
  ConsentsBucket: org-sagebridge-consents-devdevelop
  DNSHostname: bridgeserver2-devdevelop
  DNSDomain: sagebridge.org
  EC2InstanceType: t2.small
  EmailUnsubscribeToken: !ssm /bridgeserver2-common/EmailUnsubscribeToken
  Env: develop
  ExporterRequestSqsQueueUrl: https://sqs.us-east-1.amazonaws.com/420786776710/Bridge-EX-Request-develop
  HibernateConnectionPassword: !ssm /bridgeserver2-develop/HibernateConnectionPassword
  HibernateConnectionUsername: !ssm /bridgeserver2-develop/HibernateConnectionUsername
  HibernateConnectionUsessl: 'true'
  HostPostfix: -devdevelop.sagebridge.org
  NewRelicAppName: bridgeserver2-devdevelop
  NewRelicLicenseKey: !ssm /infra/NewRelicLicenseKey
  ParticipantFileBucket: org-sagebridge-participantfile-devdevelop
  SesNotificationTopicArn: arn:aws:sns:us-east-1:420786776710:SNSBounces
  SynapseApiKey: !ssm /bridgeserver2-develop/SynapseApiKey
  SynapseUser: !ssm /bridgeserver2-develop/SynapseUser
  SynapseOAuthClientId: !ssm /bridgeserver2-develop/SynapseOAuthClientId
  SynapseOAuthClientSecret: !ssm /bridgeserver2-develop/SynapseOAuthClientSecret
  UddSqsQueueUrl: https://sqs.us-east-1.amazonaws.com/420786776710/Bridge-WorkerPlatform-Request-develop
  UploadBucket: org-sagebridge-upload-devdevelop
  UploadCmsCertBucket: org-sagebridge-upload-cms-cert-devdevelop
  UploadCmsPrivBucket: org-sagebridge-upload-cms-priv-devdevelop
  UseHttpsForwarding: false
  UsersignedConsentsBucket: org-sagebridge-usersigned-consents-devdevelop
  CrcGeoCodeApiKey: !ssm /bridgeserver2-develop/CrcGeoCodeApiKey
  CuimcTestUsername: !ssm /bridgeserver2-common/CuimcTestUsername
  CuimcTestPassword: !ssm /bridgeserver2-common/CuimcTestPassword
  CuimcProdUsername: !ssm /bridgeserver2-common/CuimcProdUsername
  CuimcProdPassword: !ssm /bridgeserver2-common/CuimcProdPassword
  GbfApiKey: !ssm /bridgeserver2-common/GbfApiKey
