template_path: bridgeserver2.yaml
stack_name: bridgeserver2-develop
depedencies:
  - common/bridgeserver2-common.yaml
  - develop/bridgeserver2-db.yaml
parameters:
  AppDeployBucket: org-biaffectbridge-bridgeserver2-deployment-develop
  AppHealthcheckUrl: '/'
  AttachmentBucket: org-biaffectbridge-attachment-develop
  AwsAutoScalingMaxSize: '1'
  AwsAutoScalingMinSize: '1'
  AwsEbHealthReportingSystem: enhanced
  AwsSnsBounceNotificationEndpoint: biaffect-bridge-bounce-notifications-develop@googlegroups.com
  AwsSnsNotificationEndpoint: biaffect-bridge-ops-develop@googlegroups.com
  BootstrapAdminEmail: !ssm /bridgeserver2-develop/BootstrapAdminEmail
  BootstrapAdminPassword: !ssm /bridgeserver2-develop/BootstrapAdminPassword
  BridgeEnv: dev
  BridgeDBStackName: bridgeserver2-db-develop
  BridgeHealthcodeRedisKey: !ssm /bridgeserver2-develop/BridgeHealthcodeRedisKey
  BridgeUser: biaffect
  BucketSuffix: develop
  DNSHostname: bridgeserver2-develop
  DNSDomain: biaffectbridge.com
  EC2InstanceType: t3a.medium
  Env: develop
  ExporterRequestSqsQueueUrl: https://sqs.us-east-1.amazonaws.com/381492192635/Bridge-EX-Request-develop
  ExporterSynapseAccessToken: !ssm /bridgeserver2-develop/ExporterSynapseAccessToken
  ExporterSynapseUser: !ssm /bridgeserver2-develop/ExporterSynapseUser
  HibernateConnectionPassword: !ssm /bridgeserver2-develop/HibernateConnectionPassword
  HibernateConnectionUsername: !ssm /bridgeserver2-develop/HibernateConnectionUsername
  HibernateConnectionUsessl: 'false'
  HostPostfix: -develop.biaffectbridge.com
  SesNotificationTopicArn: arn:aws:sns:us-east-1:381492192635:SNSBounces-develop
  SynapseAccessToken: !ssm /bridgeserver2-develop/SynapseAccessToken
  SynapseUser: !ssm /bridgeserver2-develop/SynapseUser
  SynapseOAuthClientId: !ssm /bridgeserver2-develop/SynapseOAuthClientId
  SynapseOAuthClientSecret: !ssm /bridgeserver2-develop/SynapseOAuthClientSecret
  UddSqsQueueUrl: https://sqs.us-east-1.amazonaws.com/381492192635/Bridge-WorkerPlatform-Request-develop
