template_path: templates/bridgeserver2.yaml
stack_name: bridgeserver2-develop
parameters:
  AppHealthcheckUrl: '/'
  AwsAutoScalingMaxSize: '1'
  AwsAutoScalingMinSize: '1'
  AwsDefaultVpcId: vpc-0818659c21d92f2a3
  AwsEbHealthReportingSystem: enhanced
  AwsSnsBounceNotificationEndpoint: bridgepf-develop-bounce-notifications@sagebase.org
  AwsSnsNotificationEndpoint: bridgepf-develop@sagebase.org
  AwsSolutionStackName: '64bit Amazon Linux 2018.03 v3.0.1 running Tomcat 8 Java 8'
  BridgeEnv: dev
  BridgeUser: heroku
  DNSHostname: bridgeserver2-develop
  DNSDomain: sagebridge.org
  EC2InstanceType: t2.small
  Env: develop
