template_path: templates/bridgeserver2.yaml
stack_name: bridgeserver2-develop
parameters:
  AppDeployBucket: org-sagebridge-bridgeserver2-deployment-develop
  AppHealthcheckUrl: '/'
  AwsAutoScalingGroupName: awseb-e-4u5asjninp-stack-AWSEBAutoScalingGroup-ZKHLD9J648PZ
  AwsAutoScalingMaxSize: '1'
  AwsAutoScalingMinSize: '1'
  AwsLoadBalancerName: awseb-AWSEB-1USUQB98TNERI
  AwsVpcId: vpc-0818659c21d92f2a3
  AwsVpcPrivateSubnets: subnet-0226fb44adc9329c8,subnet-08ac09086998c158d,subnet-03cdb08e9a667af48
  AwsVpcPublicSubnets: subnet-00035aecc853eee0a,subnet-02e52b9bfc86ca70f,subnet-0c5a8cd4e7e1856c0
  AwsEbHealthReportingSystem: enhanced
  AwsSnsBounceNotificationEndpoint: bridgepf-develop-bounce-notifications@sagebase.org
  AwsSnsNotificationEndpoint: bridgepf-develop@sagebase.org
  AwsSolutionStackName: '64bit Amazon Linux 2018.03 v3.0.1 running Tomcat 8 Java 8'
  BridgeEnv: dev
  BridgeUser: heroku
  DNSHostname: bridgeserver2-develop
  DNSDomain: sagebridge.org
  EC2InstanceType: t2.small
  Env: develop
