template_path: bridgeserver2-db.yaml
stack_name: bridgeserver2-db-uat
depedencies:
  - common/bridgeserver2-common-db.yaml
parameters:
  HibernateConnectionPassword: !ssm /bridgeserver2-uat/HibernateConnectionPassword
  HibernateConnectionUsername: !ssm /bridgeserver2-uat/HibernateConnectionUsername
