template_path: templates/bridgeserver2.yaml
stack_name: bridgeserver2-uat
parameters:
  AppHealthcheckUrl: 'HTTP:80/?study=api'
  AwsAutoScalingMaxSize: '1'
  AwsAutoScalingMinSize: '1'
  AwsDefaultVpcId: vpc-9c70bbf9
  AwsEbHealthReportingSystem: enhanced
  AwsSnsBounceNotificationEndpoint: bridgepf-uat-bounce-notifications@sagebase.org
  AwsSnsNotificationEndpoint: bridgepf-uat@sagebase.org
  AwsSolutionStackName: '64bit Amazon Linux 2018.03 v3.0.1 running Tomcat 8 Java 8'
  BridgeEnv: uat
  BridgeUser: heroku
  DNSHostname: bridgeserver2-uat
  DNSDomain: sagebridge.org
  EC2InstanceType: t2.small
  Env: staging
