Description: Common resources for BridgeServer2 databases
AWSTemplateFormatVersion: 2010-09-09
Resources:
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: 'Subnet for Server2 VPC'
      DBSubnetGroupName: 'bridgeserver2-rds-subnet'
      SubnetIds:
        - 'subnet-0c914eb7292a302fc'
        - 'subnet-09790b48060420f4c'
        - 'subnet-074665325c1b2aa25'
Outputs:
  DBSubnetGroupName:
    Value: !Ref DBSubnetGroup
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-DBSubnetGroupName'
