Description: Load balancer HTTPS redirect
AWSTemplateFormatVersion: 2010-09-09
Parameters:
  LoadBalancerArn:
    Type: String
Resources:
  HttpsRedirectListener:
     Type: "AWS::ElasticLoadBalancingV2::Listener"
     Properties:
       DefaultActions:
         - Type: "redirect"
           RedirectConfig:
             Protocol: "HTTPS"
             Port: "443"
             Host: "#{host}"
             Path: "/#{path}"
             Query: "#{query}"
             StatusCode: "HTTP_301"
       LoadBalancerArn: !Ref LoadBalancerArn
       Port: 80
       Protocol: "HTTP"
Outputs:
  HttpsRedirectListener:
    Value: !Ref HttpsRedirectListener
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-HttpsRedirectListener'
